# Generated by Django 4.0.2 on 2022-03-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wGOA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpc',
            name='Time',
        ),
    ]
