# Generated by Django 4.0.2 on 2022-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wGOA', '0003_cpc_time'),
    ]

    operations = [

        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),

    ]
