# Generated by Django 4.0.2 on 2022-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wGOA', '0003_cpc_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='aps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('d1', models.CharField(max_length=15)),
                ('d2', models.CharField(max_length=15)),
                ('d3', models.CharField(max_length=15)),
                ('d4', models.CharField(max_length=15)),
                ('d5', models.CharField(max_length=15)),
                ('d6', models.CharField(max_length=15)),
                ('d7', models.CharField(max_length=15)),
                ('d8', models.CharField(max_length=15)),
                ('d9', models.CharField(max_length=15)),
                ('d10', models.CharField(max_length=15)),
                ('d11', models.CharField(max_length=15)),
                ('d12', models.CharField(max_length=15)),
                ('d13', models.CharField(max_length=15)),
                ('d14', models.CharField(max_length=15)),
                ('d15', models.CharField(max_length=15)),
                ('d16', models.CharField(max_length=15)),
                ('d17', models.CharField(max_length=15)),
                ('d18', models.CharField(max_length=15)),
                ('d19', models.CharField(max_length=15)),
                ('d20', models.CharField(max_length=15)),
                ('d21', models.CharField(max_length=15)),
                ('d22', models.CharField(max_length=15)),
                ('d23', models.CharField(max_length=15)),
                ('d24', models.CharField(max_length=15)),
                ('d25', models.CharField(max_length=15)),
                ('d26', models.CharField(max_length=15)),
                ('d27', models.CharField(max_length=15)),
                ('d28', models.CharField(max_length=15)),
                ('d29', models.CharField(max_length=15)),
                ('d30', models.CharField(max_length=15)),
                ('d31', models.CharField(max_length=15)),
                ('d32', models.CharField(max_length=15)),
                ('d33', models.CharField(max_length=15)),
                ('d34', models.CharField(max_length=15)),
                ('d35', models.CharField(max_length=15)),
                ('d36', models.CharField(max_length=15)),
                ('d37', models.CharField(max_length=15)),
                ('d38', models.CharField(max_length=15)),
                ('d39', models.CharField(max_length=15)),
                ('d40', models.CharField(max_length=15)),
                ('d41', models.CharField(max_length=15)),
                ('d42', models.CharField(max_length=15)),
                ('d43', models.CharField(max_length=15)),
                ('d44', models.CharField(max_length=15)),
                ('d45', models.CharField(max_length=15)),
                ('d46', models.CharField(max_length=15)),
                ('d47', models.CharField(max_length=15)),
                ('d48', models.CharField(max_length=15)),
                ('d49', models.CharField(max_length=15)),
                ('d50', models.CharField(max_length=15)),
                ('d51', models.CharField(max_length=15)),
                ('d52', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'aps_ubi',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cpc2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('N', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cpc_ubi_1',
            },
        ),
        migrations.CreateModel(
            name='neph2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('sblue', models.CharField(max_length=15)),
                ('sred', models.CharField(max_length=15)),
                ('sgreen', models.CharField(max_length=15)),
                ('bsblue', models.CharField(max_length=15)),
                ('bsred', models.CharField(max_length=15)),
                ('bsgreen', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'neph_ubi_1',
            },
        ),
        migrations.CreateModel(
            name='psap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('blue', models.CharField(max_length=15)),
                ('red', models.CharField(max_length=15)),
                ('green', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'psap_ubi',
            },
        ),
    ]
