# Generated by Django 4.0.2 on 2022-04-04 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wGOA', '0004_aps_contact_cpc2_neph2_psap'),
    ]

    operations = [

    ]
